#!/usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

use Illuminate\Console\Application;
use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;
use Symfony\Component\Finder\Finder;

$finder = new Finder();
$finder->files()->in(__DIR__ . '/app/Console/Commands/')->name('*.php');

$container = new Container();
$dispatcher = new Dispatcher($container);
$application = new Application($container, $dispatcher, 'JMFramework', '1.1.0');

foreach ($finder as $file) {
    $commandClass = 'App\Console\Commands\\' . $file->getBasename('.php');
    if (class_exists($commandClass)) {
        $application->add(new $commandClass());
    }
}

$application->run();
